name: taptrack_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  firebase_core: any
  firebase_auth: any
  firebase_database: any
  flutter_bloc: any
  bloc: any
  provider: any
  get_it: any
  injectable: any
  go_router: any
  go_router_builder: any
  freezed_annotation: any
  json_annotation: '>=4.9.0 <5.0.0'
  gap: any
  google_fonts: any
  flutter_svg: any
  flutter_staggered_grid_view: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any
  build_runner: any
  injectable_generator: any
  json_serializable: '>=6.7.0 <7.0.0'
  freezed: any

flutter:
  uses-material-design: true
