// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLtOgdEJKVre8tbbd3iEO8fN5PE30ZNm4',
    appId: '1:11812583821:web:78a87d81e34807a4a4e5c4',
    messagingSenderId: '11812583821',
    projectId: 'taptrackapp-38817',
    authDomain: 'taptrackapp-38817.firebaseapp.com',
    storageBucket: 'taptrackapp-38817.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAES_IjaB8IPsle8nzpLD2-halGPrtk7Bo',
    appId: '1:11812583821:android:53a455e53ef10f81a4e5c4',
    messagingSenderId: '11812583821',
    projectId: 'taptrackapp-38817',
    storageBucket: 'taptrackapp-38817.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB82xmhR0f4Z8hpzPgzqmQzYcl83dnvVCU',
    appId: '1:11812583821:ios:5668e7466f4e20a3a4e5c4',
    messagingSenderId: '11812583821',
    projectId: 'taptrackapp-38817',
    storageBucket: 'taptrackapp-38817.firebasestorage.app',
    iosBundleId: 'com.example.taptrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB82xmhR0f4Z8hpzPgzqmQzYcl83dnvVCU',
    appId: '1:11812583821:ios:5668e7466f4e20a3a4e5c4',
    messagingSenderId: '11812583821',
    projectId: 'taptrackapp-38817',
    storageBucket: 'taptrackapp-38817.firebasestorage.app',
    iosBundleId: 'com.example.taptrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLtOgdEJKVre8tbbd3iEO8fN5PE30ZNm4',
    appId: '1:11812583821:web:cf37f6b611570f78a4e5c4',
    messagingSenderId: '11812583821',
    projectId: 'taptrackapp-38817',
    authDomain: 'taptrackapp-38817.firebaseapp.com',
    storageBucket: 'taptrackapp-38817.firebasestorage.app',
  );
}
